### ISSUE TITLE
Local modules directory name (luarocks_modules) does conflict with the 'luarocks init' one (lua_modules)

### ISSUE THREAD

**Issue by bojh** [Propagram/ZeroBranePackage-LuaRocks#1]
to work together with a project setup via luarocks like 
`>> luarocks init`
does create an `lua_modules` directory in the project working directory - while the current LuaRocks.lua module implementation does assume/create a `luarocks_modules` directory.
I would ask for getting this aligned.

**Comment by Propagram** [comment]
Fixed. Thanks!

**Comment by bojh** [comment]
Fine - works well! THX
