### ISSUE TITLE
select 'IDE Packages' does implicit set lua version for the plugin to '5.1', while selcted version is different

### ISSUE THREAD

**Issue by bojh** [Propagram/ZeroBranePackage-LuaRocks#2]
status ZeroBrandStudio:
- Project-LuaInterpreter: Lua 5.4
- Project Modules shows_ "x modules found (Lua 5.4)"
- UserModules shows:  "x modules found (Lua 5.4)"

select "IDE Packages"...
- Project Modules shows_ "x modules found (Lua 5.1)"
- UserModules shows:  "x modules found (Lua 5.1)"

**Comment by Propagram** [comment]
This is an expected behavior. ZeroBrane Studio's internal interpreter is LuaJIT (compatible with Lua 5.1).

I'm considering removing the interpreter version label from the "IDE Packages" to avoid confusion.

**Comment by Propagram** [comment]
Good catch! Fixed. Thanks!

Could you update this module and test to verify if it is behaving correctly now? :)

**Comment by bojh** [comment]
Thanks for the fast response.
ZBS starts in the LuRocks-Plugin with "Project Modules (Lua 5.4)". I then switch to "IDE Packages" gives info "(Lua 5.1)" After some in-between also Project-Modules get (Lua5.1) again - from my point of view not what was expected.

**Comment by Propagram** [comment]
Thanks for the report. I confirmed this issue as well. I rewrote the code for the 'IDE Packages' tab so that this doesn't happen anymore. Can you confirm for me if it's okay after updating the package again?

**Comment by bojh** [comment]
Looks very good! Fine! .. as expected! - THX
The questions is how to deal with "IDE Packages". From the log in the terminal, you could see that 5.1 is retrieved. For me it seems reasonable to show than also "(Lua 5.1)" - alternatively all are handled in the same way and IDE will be empty for >5.1.

What also could be a good idea: To provide a possibility (toggle button)  to include the repos to the package.path and package.cpath for execution/debug. That would be really nice!!

**Comment by Propagram** [comment]
> Looks very good! Fine! .. as expected! - THX

Great. Thank you for testing!

> The questions is how to deal with "IDE Packages". From the log in the terminal, you could see that 5.1 is retrieved. For me it seems reasonable to show than also "(Lua 5.1)"

The 'IDE Packages' tab was quite challenging to implement. ZeroBrane's packages must always be installed in the same version as the IDE interpreter (Lua[JIT] 5.1). Therefore, when changing the interpreter, one should always revert to Lua 5.1 when accessing this tab.

>  - alternatively all are handled in the same way and IDE will be empty for >5.1.

I understand. For example, if I install the 'document map' package, but my project uses Lua 5.4, it doesn't make sense for me to have to change the interpreter to Lua 5.1, remove the package, and then revert again.

It is convenient for this plugin to make this temporary change automatically.

I can add a label in the 'IDE Packages' tab with (ZBS Lua version: 5.1) to imply that it refers to the IDE's internal Lua interpreter.

> What also could be a good idea: To provide a possibility (toggle button) to include the repos to the package.path and package.cpath for execution/debug. That would be really nice!!

Good idea. Currently, I don't have time to make such significant changes :)

An alternative is to manually edit the 'packages.path' with the modules you want to debug. Or, temporarily uninstall the modules and leave only the desired ones.

-- Thanks!

**Comment by bojh** [comment]
would like it for the IDE packages: "(ZBS lua 5.1)"
a great step forward  - Thanks a lot!

**Comment by Propagram** [comment]
> would like it for the IDE packages: "(ZBS lua 5.1)"

Added. Now displays *(ZBS Lua 5.1)* in the IDE Packages tab. It relies on Lua's `_VERSION`.

-- Thank you for the suggestions!
